### ISSUE TITLE
Not Work on Nexus 5 device 

### ISSUE THREAD

**Issue by bhoomikaPrajapati** [abangfadli/shotwatch#1]

**Comment by abangfadli** [comment]
Hi @bhoomikaPrajapati thanks for your report. Do you get any output on the logcat?
And what is the device OS version + your device language? Thanks.

**Comment by overhound** [comment]
Have you been able to fix this? @abangfadli

**Comment by abangfadli** [comment]
@overhound Info on the OS version + device language would be helpful. Tried successfully on Nexus 5 with OS 8.0.0 with (en-US).

**Comment by abangfadli** [comment]
Closing this as I can't reproduce. Feel free to re-open if anyone found the same issue.
